[nltk_data] Downloading package wordnet to
[nltk_data]     /cluster/raid/home/michael.tsesmelis/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /cluster/raid/home/michael.tsesmelis/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
  0%|          | 0/18 [00:00<?, ?it/s]/cluster/raid/home/michael.tsesmelis/SideProject/ML.py:75: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset["output"] = predictions
  0%|          | 0/18 [01:23<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 129, in <module>
    
  File "main.py", line 106, in managerial_layer
    print("2. Preparing CPC clusters ({})".format(datetime.now()))
  File "/cluster/raid/home/michael.tsesmelis/SideProject/ML.py", line 168, in run_ML
    time_series, tensors["patent"] = calculate_indicators(ml_df,
  File "/cluster/raid/home/michael.tsesmelis/SideProject/ML.py", line 109, in calculate_indicators
    df_final, tensor_patent = calculate_emergingness(ml_df, tensor_patent, from_files=False)
  File "/cluster/raid/home/michael.tsesmelis/SideProject/ML.py", line 78, in calculate_emergingness
    df = pd.concat([df, subset], axis=0)
UnboundLocalError: local variable 'df' referenced before assignment
